version: '2'
services:
    swell-app:
        image: swell
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://swell-mysql:3306/swell?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    swell-mysql:
        extends:
            file: mysql.yml
            service: swell-mysql
